CREATE TABLE USERS(ID_USER INT PRIMARY KEY,
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
PHONENUM BIGINT NOT NULL,
USER_PASSWORD VARCHAR(15) NOT NULL);

CREATE TABLE DOCTORS(ID_DOCTOR INT PRIMARY KEY,
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
PHONENUM BIGINT NOT NULL,
CABNUM TINYINT NOT NULL,
SPECIALITY VARCHAR(30) NOT NULL,
DOC_PASSWORD VARCHAR(15) NOT NULL);

CREATE TABLE USER_DOCTOR(USER_ID INT NOT NULL,
DOCTOR_ID INT NOT NULL,
FOREIGN KEY(USER_ID)
   REFERENCES USERS(ID_USER),
FOREIGN KEY(DOCTOR_ID)
   REFERENCES DOCTORS(ID_DOCTOR));

CREATE TABLE TIMESLOT(ID INT PRIMARY KEY,
DAY_OF_WEEK VARCHAR(10) NOT NULL,
START_WORKHOUR INT NOT NULL,
END_WORKHOUR INT NOT NULL);

CREATE TABLE DOC_TIMESLOT(DOCTOR_ID INT NOT NULL,
TIMESLOT_ID INT NOT NULL,
FOREIGN KEY(DOCTOR_ID)
   REFERENCES DOCTORS(ID_DOCTOR),
FOREIGN KEY(TIMESLOT_ID)
   REFERENCES TIMESLOT(ID));

CREATE TABLE DOC_RECEPTION(DOCTOR_ID INT NOT NULL,
USER_ID INT NOT NULL,
RECEPTION_TIME INT NOT NULL,
FOREIGN KEY(DOCTOR_ID)
   REFERENCES DOCTORS(ID_DOCTOR),
FOREIGN KEY(USER_ID)
   REFERENCES USERS(ID_USER));

CREATE TABLE PATIENTCARDS(DOCTOR_ID INT NOT NULL,
USER_ID INT NOT NULL,
NOTE_ID INT NOT NULL,
FOREIGN KEY(DOCTOR_ID)
   REFERENCES DOCTORS(ID_DOCTOR),
FOREIGN KEY(USER_ID)
   REFERENCES USERS(ID_USER));

CREATE TABLE VERSION(ID INT PRIMARY KEY,
VERSION_NUM VARCHAR(30) NOT NULL);

INSERT INTO DOCTORS(ID_DOCTOR, FIRSTNAME, LASTNAME, PHONENUM, CABNUM, SPECIALITY, DOC_PASSWORD)
VALUES(1, 'Taras', 'Banan', 380983925789, 100, 'Dentist', 'BLABLABLA');

INSERT INTO DOCTORS(ID_DOCTOR, FIRSTNAME, LASTNAME, PHONENUM, CABNUM, SPECIALITY, DOC_PASSWORD)
VALUES(2, 'Oleg', 'Kolobok', 380936836523, 101, 'Dentist', 'BYBYBY');

INSERT INTO DOCTORS(ID_DOCTOR, FIRSTNAME, LASTNAME, PHONENUM, CABNUM, SPECIALITY, DOC_PASSWORD)
VALUES(3, 'QUEEN', 'Angry', 380952154876, 102, 'Dentist-surgeon', 'Rock-n-roll');


